# Generated by Django 2.2.4 on 2021-01-25 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoke', models.IntegerField()),
                ('tendency', models.CharField(max_length=15)),
                ('lifetime', models.CharField(max_length=20)),
                ('student_ID', models.CharField(max_length=45)),
                ('major', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('religion', models.IntegerField()),
                ('labtop', models.IntegerField()),
                ('sleepinghabit', models.IntegerField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.Room')),
            ],
        ),
    ]
